### ISSUE TITLE
Feature Request: Ability to specify -n headers to skip

### ISSUE THREAD

**Issue by AurielleP** [DataFoxCo/gocsv#1]
Would like to be able to specify how many rows to skip before performing a task, for situations where an export I am editing has more than 1 header.

**Comment by aotimme** [comment]
I believe you can currently do this via multiple uses of the `behead` subcommand. If you want to remove one header, then use
```
behead input.csv > output.csv
```
If you want to remove two headers, then
```
behead input.csv | behead > output.csv
```
etc.

We can add a `-n` flag to the `behead` subcommand though to provide a shorthand for doing the chained piping. With this, in order to remove _N_ headers, you would use
```
behead -n N input.csv > output.csv
```
Would that be a good solution?

**Comment by AurielleP** [comment]
Yes that sounds like a great solution :)
